# Generated by Django 2.2.1 on 2019-05-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetris', '0002_auto_20190515_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
