# Generated by Django 2.2.1 on 2019-05-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetris', '0003_auto_20190515_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgame',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
    ]
